In [1]:
import numpy as np

x = np.array([[2,0]])
rotation = np.array([ [0,-1],
                      [1, 0]])

In [4]:
#Problem 1
print(x*rotation)
print(rotation*x)
#These two results are same because * operation mutiply the value on the same position of each vector.
#Thus, the multiply processes [2,0] and [0,-1], then [2,0] and [1,0]

[[0 0]
 [2 0]]
[[0 0]
 [2 0]]


In [8]:
#Problem 2
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

x.reshape(-1,order='F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [7]:
#Problem 3
x2.reshape(-1,order='F').reshape(4,3)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [9]:
#Problem 4
def naive_matrix_dot(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]
  
  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, column_y)
  return z
def naive_vector_dot(x, y):
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]
  
  z = 0.
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

In [12]:
x_10 = np.ones((10,10))
y_10 = np.ones((10,10))

x_100 = np.ones((100,100))
y_100 = np.ones((100,100))

x_1000 = np.ones((1000,1000))
y_1000 = np.ones((1000,1000))

In [21]:
import time

start = time.process_time()
naive_matrix_dot(x_10,y_10)
print("naive function 10x10:", time.process_time()-start,2)
start = time.process_time()
naive_matrix_dot(x_100,y_100)
print("naive function 100x100:", time.process_time() - start, 2)
#start = time.process_time()
#naive_matrix_dot(x_1000,y_1000)
#print("naive function 1000x1000:", time.process_time() - start, 2)
#It takes more than a minute

start_2 = time.process_time()
np.matmul(x_10,y_10)
print("built in function 10x10:", time.process_time() - start_2,2)
start_2 = time.process_time()
np.matmul(x_100,y_100)
print("built in function 100x100:", time.process_time() - start_2,2)
start_2 = time.process_time()
np.matmul(x_1000,y_1000)
print("built in function 1000x1000:", time.process_time() - start_2,2)

naive function 10x10: 0.0 2
naive function 100x100: 0.34375 2
built in function 10x10: 0.0 2
built in function 100x100: 0.0 2
built in function 1000x1000: 0.125 2


In [22]:
#Problem 5
import tensorflow as tf

from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images,test_labels) = mnist.load_data()

from tensorflow.keras import models
from tensorflow.keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

import time

start = time.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = time.time() - start

print('Elapsed time: %.4f' % elapsed)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc: ', test_acc)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 4s 62us/sample - loss: 0.2559 - acc: 0.9268
Epoch 2/5
60000/60000 [==============================] - 3s 58us/sample - loss: 0.1034 - acc: 0.9691
Epoch 3/5
60000/60000 [==============================] - 4s 61us/sample - loss: 0.0673 - acc: 0.9796
Epoch 4/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0494 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0375 - acc: 0.9886
Elapsed time: 18.8236
10000/10000 [==============================] - 1s 71us/sample - loss: 0.0652 - acc: 0.9797
test_acc:  0.9797


In spyder it takes 17.0165s