In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [3]:
from sklearn.base import BaseEstimator,TransformerMixin
class removename(BaseEstimator,TransformerMixin):
    def __init__(self):
        self.names = []
    def fit(self,X,y=None):
        return self
    def transform(self,X,y=None):
        for name_id in range(len(X['Name'])):
            self.names.append(X['Name'][name_id].split(',')[0])
        X['Name'] = self.names
        return X

In [63]:
n = removename()
n.transform(data)

PassengerId  Survived  Pclass             Name     Sex   Age  SibSp  \
0              1         0       3           Braund    male  22.0      1   
1              2         1       1          Cumings  female  38.0      1   
2              3         1       3        Heikkinen  female  26.0      0   
3              4         1       1         Futrelle  female  35.0      1   
4              5         0       3            Allen    male  35.0      0   
5              6         0       3            Moran    male   NaN      0   
6              7         0       1         McCarthy    male  54.0      0   
7              8         0       3          Palsson    male   2.0      3   
8              9         1       3          Johnson  female  27.0      0   
9             10         1       2           Nasser  female  14.0      1   
10            11         1       3        Sandstrom  female   4.0      1   
11            12         1       1          Bonnell  female  58.0      0   
12            13         0       3      Saundercock    male  20.0      0   
13            14         0       3        Andersson    male  39.0      1   
14            15         0       3          Vestrom  female  14.0      0   
15            16         1       2          Hewlett  female  55.0      0   
16            17         0       3             Rice    male   2.0      4   
17            18         1       2         Williams    male   NaN      0   
18            19         0       3    Vander Planke  female  31.0      1   
19            20         1       3       Masselmani  female   NaN      0   
20            21         0       2           Fynney    male  35.0      0   
21            22         1       2          Beesley    male  34.0      0   
22            23         1       3          McGowan  female  15.0      0   
23            24         1       1           Sloper    male  28.0      0   
24            25         0       3          Palsson  female   8.0      3   
25            26         1       3          Asplund  female  38.0      1   
26            27         0       3             Emir    male   NaN      0   
27            28         0       1          Fortune    male  19.0      3   
28            29         1       3          O'Dwyer  female   NaN      0   
29            30         0       3         Todoroff    male   NaN      0   
..           ...       ...     ...              ...     ...   ...    ...   
861          862         0       2            Giles    male  21.0      1   
862          863         1       1            Swift  female  48.0      0   
863          864         0       3             Sage  female   NaN      8   
864          865         0       2             Gill    male  24.0      0   
865          866         1       2          Bystrom  female  42.0      0   
866          867         1       2     Duran y More  female  27.0      1   
867          868         0       1         Roebling    male  31.0      0   
868          869         0       3    van Melkebeke    male   NaN      0   
869          870         1       3          Johnson    male   4.0      1   
870          871         0       3           Balkic    male  26.0      0   
871          872         1       1         Beckwith  female  47.0      1   
872          873         0       1         Carlsson    male  33.0      0   
873          874         0       3  Vander Cruyssen    male  47.0      0   
874          875         1       2          Abelson  female  28.0      1   
875          876         1       3            Najib  female  15.0      0   
876          877         0       3       Gustafsson    male  20.0      0   
877          878         0       3          Petroff    male  19.0      0   
878          879         0       3           Laleff    male   NaN      0   
879          880         1       1           Potter  female  56.0      0   
880          881         1       2          Shelley  female  25.0      0   
881          882         0       3           Markun  

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

class AttributesAdder(BaseEstimator,TransformerMixin):
    def __init__(self):
        self.family = []
    def fit(self,X,y=None):
        pass
    def transform(self,X,y=None):
        for idx in range(len(X['SibSp'])):
            self.family.append(X['SibSp'][idx] + X['Parch'][idx])
        X['Family'] = self.family
        del X['SibSp'] , X['Parch']
        return X
    
class Selector(BaseEstimator,TransformerMixin):
    def __init__(self,col_names):
        self.col_names = col_names
    def fit(self,X,y=None):
        return self
    def transform(self,X):
        return X[self.col_names].values

In [5]:
numeric_col = ['Age','Fare']
numeric_transformer = Pipeline([
    ('selector',Selector(numeric_col)),
    ('imputer',SimpleImputer(strategy='median')),
    ('std_scaler',StandardScaler()),
])
categorical_col = ['Sex','Embarked','Pclass']
categorical_transformer = Pipeline([
    ('selector',Selector(categorical_col)),
    ('imputer',SimpleImputer(strategy='constant',fill_value='missing')),
    ('encoder',OneHotEncoder(handle_unknown='ignore')),
])

preprocessor = ColumnTransformer([
    ('num',numeric_transformer,numeric_col),
    ('cat',categorical_transformer,categorical_col),
])

clf = Pipeline([
    ('prepro',preprocessor),
])

In [6]:
aa = AttributesAdder()

In [7]:
aa.transform(data)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  \
0                              Braund, Mr. Owen Harris    male  22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                               Heikkinen, Miss. Laina  female  26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                             Allen, Mr. William Henry    male  35.0   
5                                     Moran, Mr. James    male   NaN   
6                              McCarthy, Mr. Timothy J    male  54.0   
7                       Palsson, Master. Gosta Leonard    male   2.0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0   
11                            Bonnell, Miss. Elizabeth  female  58.0   
12                      Saundercock, Mr. William Henry    male  20.0   
13                         Andersson, Mr. Anders Johan    male  39.0   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
16                                Rice, Master. Eugene    male   2.0   
17                        Williams, Mr. Charles Eugene    male   NaN   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
19                             Masselmani, Mrs. Fatima  female   NaN   
20                                Fynney, Mr. Joseph J    male  35.0   
21                               Beesley, Mr. Lawrence    male  

In [18]:
data.head()

PassengerId  Survived  Pclass       Name     Sex   Age            Ticket  \
0            1         0       3     Braund    male  22.0         A/5 21171   
1            2         1       1    Cumings  female  38.0          PC 17599   
2            3         1       3  Heikkinen  female  26.0  STON/O2. 3101282   
3            4         1       1   Futrelle  female  35.0            113803   
4            5         0       3      Allen    male  35.0            373450   

      Fare Cabin Embarked  Family  
0   7.2500   NaN        S       1  
1  71.2833   C85        C       1  
2   7.9250   NaN        S       0  
3  53.1000  C123        S       1  
4   8.0500   NaN        S       0

In [8]:
y = data['Survived'].copy()

In [68]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [9]:
prepare = clf.fit_transform(data)

In [10]:
df = pd.DataFrame(prepare)

In [11]:
df.columns = [['Age','Fare','Female','Male','Embarked_C','Embarked_Q','Embared_S','Pclass_0','Pclass_1','Pclass_2','Pclass_3']]

In [12]:
df.drop('Pclass_0',inplace=True,axis=1)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\pandas\core\generic.py:3111: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [13]:
df.index = data['PassengerId']

In [14]:
df['Family'] = data['Family']

In [136]:
def repl(X,col_name):
    for idx in range(len(X[col_name])):
        if pd.isna(X[col_name][idx]) == False:
            X[col_name][idx] = 1
        else:
            X[col_name][idx] = 0
    return X

In [245]:
df.tail()

Age      Fare Female Male Embarked_C Embarked_Q Embared_S Pclass_1  \
886 -0.181487 -0.386671    0.0  1.0        0.0        0.0       1.0      0.0   
887 -0.796286 -0.044381    1.0  0.0        0.0        0.0       1.0      1.0   
888 -0.104637 -0.176263    1.0  0.0        0.0        0.0       1.0      0.0   
889 -0.258337 -0.044381    0.0  1.0        1.0        0.0       0.0      1.0   
890  0.202762 -0.492378    0.0  1.0        0.0        1.0       0.0      0.0   

    Pclass_2 Pclass_3 Family  
886      1.0      0.0      0  
887      0.0      0.0      0  
888      0.0      1.0      3  
889      0.0      0.0      0  
890      0.0      1.0      0

In [15]:
df['Cabin']=(data['Cabin'].isna() == True).astype(int)

In [17]:
df.fillna(0, inplace=True)

In [18]:
X = df.copy()

In [19]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

In [20]:
log_reg.fit(X,y)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
prediction = log_reg.predict(X)

In [263]:
prediction

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,

In [22]:
log_reg.score(X,y)

0.792368125701459

In [35]:
log_rmse

0.45566640681373577

In [23]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg,X,y,scoring="neg_mean_squared_error",cv=10)
log_rmse_scores = np.sqrt(-scores)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to '

In [24]:
log_rmse_scores

array([0.48304589, 0.45946829, 0.47404546, 0.39661489, 0.43704832,
       0.46204236, 0.48575205, 0.48575205, 0.44971901, 0.45226702])

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
forest_reg = RandomForestClassifier(n_estimators=10)
forest_reg.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:
forest_reg.predict(X)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [26]:
forest_reg.score(X,y)

0.9753086419753086

In [42]:
forest_scores = cross_val_score(forest_reg,X,y,scoring="neg_mean_squared_error",cv=10)
forest_rmse_score = np.sqrt(-forest_scores)

In [43]:
forest_rmse_score

array([0.48304589, 0.43461349, 0.49718308, 0.36719404, 0.33520076,
       0.44971901, 0.43704832, 0.48575205, 0.44971901, 0.41286141])

In [48]:
predicts = pd.DataFrame(log_reg.predict(X))

In [53]:
predicts.columns = ['log_reg']

In [54]:
predicts['forest_reg'] = forest_reg.predict(X)
predicts['Real'] = y

In [145]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'C':np.logspace(-20,20,5),
     'penalty':['l1','l2']}
]
grid_search = GridSearchCV(log_reg,param_grid,cv=10,n_jobs=1)
grid_search.fit(df,y)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to '

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to '

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to '

GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=1,
       param_grid=[{'C': array([1.e-20, 1.e-10, 1.e+00, 1.e+10, 1.e+20]), 'penalty': ['l1', 'l2']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [146]:
grid_search.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [153]:
final_model = grid_search.best_estimator_
grid_search.best_estimator_

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [71]:
bb = AttributesAdder()

In [72]:
bb.transform(test)

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [73]:
prepare_test = clf.fit_transform(test)
prepare_test

array([[ 0.38623105, -0.49741333,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.37137004, -0.51227801,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 2.55353683, -0.46410047,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.70147553, -0.50779638,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [-0.20485235, -0.49345515,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [-0.20485235, -0.23695704,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

In [74]:
df_test = pd.DataFrame(prepare_test)
df_test

0         1    2    3    4    5    6    7    8    9
0    0.386231 -0.497413  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
1    1.371370 -0.512278  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
2    2.553537 -0.464100  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
3   -0.204852 -0.482475  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
4   -0.598908 -0.417492  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
5   -1.229397 -0.472391  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
6    0.031581 -0.500999  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
7   -0.283663 -0.117894  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
8   -0.914152 -0.508169  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
9   -0.677719 -0.204838  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
10  -0.204852 -0.496219  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
11   1.292559 -0.171674  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
12  -0.520097  0.836992  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
13   2.632348 -0.171674  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
14   1.371370  0.458892  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
15  -0.441286 -0.140826  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
16   0.425637 -0.416371  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
17  -0.677719 -0.508245  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
18  -0.204852 -0.495696  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
19   1.213748 -0.508245  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
20   2.001859  0.427072  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
21  -1.623452 -0.580922  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
22  -0.204852 -0.069792  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
23  -0.677719  0.462552  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
24   1.450181  4.065709  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
25   1.607803 -0.377829  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
26  -0.598908  0.473308  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
27  -0.559502 -0.508245  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
28   0.898503 -0.091005  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
29  -0.204852 -0.249131  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...  ...  ...
388 -0.677719 -0.498833  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
389 -1.859886 -0.259962  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
390 -0.520097  1.038366  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
391  1.686615  0.068541  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
392 -1.308208 -0.274752  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
393  1.371370 -0.449535  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
394 -0.047230 -0.242932  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
395 -0.914152  0.437828  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
396 -0.441286 -0.507796  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
397  1.450181  0.782017  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
398 -0.598908 -0.498385  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
399  0.110392 -0.499132  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
400  0.031581  2.317724  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
401  0.662070 -0.261307  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
402 -0.598908  0.427072  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
403 -0.992964  0.206576  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
404  1.056126 -0.140826  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
405 -0.756530 -0.389257  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
406 -0.520097 -0.449535  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
407  1.607803  3.153697  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
408 -0.204852 -0.499357  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
409 -2.096319 -0.390826  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
410 -0.204852 -0.498833  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
411  0.583259  0.975624  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
412 -0.126041 -0.498385  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
413 -0.204852 -0.493455  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
414  0.740881  1.314435  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
415  0.701476 -0.507796  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
416 -0.204852 -0.493455  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
417 -0.204852 -0.236957  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0

[418 rows x 10 columns]

In [75]:
df_test.columns = [['Age','Fare','Female','Male','Embarked_C','Embarked_Q','Embared_S','Pclass_1','Pclass_2','Pclass_3']]

In [76]:
df_test['Family'] = test['Family']

In [77]:
df_test['Cabin'] = test['Cabin']

In [78]:
df_test['Cabin']=(df_test['Cabin'].isna()==True).astype(int)

In [79]:
df_test

Age      Fare Female Male Embarked_C Embarked_Q Embared_S Pclass_1  \
0    0.386231 -0.497413    0.0  1.0        0.0        1.0       0.0      0.0   
1    1.371370 -0.512278    1.0  0.0        0.0        0.0       1.0      0.0   
2    2.553537 -0.464100    0.0  1.0        0.0        1.0       0.0      0.0   
3   -0.204852 -0.482475    0.0  1.0        0.0        0.0       1.0      0.0   
4   -0.598908 -0.417492    1.0  0.0        0.0        0.0       1.0      0.0   
5   -1.229397 -0.472391    0.0  1.0        0.0        0.0       1.0      0.0   
6    0.031581 -0.500999    1.0  0.0        0.0        1.0       0.0      0.0   
7   -0.283663 -0.117894    0.0  1.0        0.0        0.0       1.0      0.0   
8   -0.914152 -0.508169    1.0  0.0        1.0        0.0       0.0      0.0   
9   -0.677719 -0.204838    0.0  1.0        0.0        0.0       1.0      0.0   
10  -0.204852 -0.496219    0.0  1.0        0.0        0.0       1.0      0.0   
11   1.292559 -0.171674    0.0  1.0        0.0        0.0       1.0      1.0   
12  -0.520097  0.836992    1.0  0.0        0.0        0.0       1.0      1.0   
13   2.632348 -0.171674    0.0  1.0        0.0        0.0       1.0      0.0   
14   1.371370  0.458892    1.0  0.0        0.0        0.0       1.0      1.0   
15  -0.441286 -0.140826    1.0  0.0        1.0        0.0       0.0      0.0   
16   0.425637 -0.416371    0.0  1.0        0.0        1.0       0.0      0.0   
17  -0.677719 -0.508245    0.0  1.0        1.0        0.0       0.0      0.0   
18  -0.204852 -0.495696    1.0  0.0        0.0        0.0       1.0      0.0   
19   1.213748 -0.508245    1.0  0.0        1.0        0.0       0.0      0.0   
20   2.001859  0.427072    0.0  1.0        1.0        0.0       0.0      1.0   
21  -1.623452 -0.580922    0.0  1.0        0.0        0.0       1.0      0.0   
22  -0.204852 -0.069792    1.0  0.0        0.0        0.0       1.0      1.0   
23  -0.677719  0.462552    0.0  1.0        1.0        0.0       0.0      1.0   
24   1.450181  4.065709    1.0  0.0        1.0        0.0       0.0      1.0   
25   1.607803 -0.377829    0.0  1.0        0.0        0.0       1.0      0.0   
26  -0.598908  0.473308    1.0  0.0        1.0        0.0       0.0      1.0   
27  -0.559502 -0.508245    0.0  1.0        1.0        0.0       0.0      0.0   
28   0.898503 -0.091005    0.0  1.0        0.0        0.0       1.0      1.0   
29  -0.204852 -0.249131    0.0  1.0        1.0        0.0       0.0      0.0   
..        ...       ...    ...  ...        ...        ...       ...      ...   
388 -0.677719 -0.498833    0.0  1.0        0.0        1.0       0.0      0.0   
389 -1.859886 -0.259962    0.0  1.0        0.0        0.0       1.0      0.0   
390 -0.520097  1.038366    0.0  1.0        0.0        0.0       1.0      1.0   
391  1.686615  0.068541    1.0  0.0        0.0        0.0       1.0      1.0   
392 -1.308208 -0.274752    0.0  1.0        0.0        0.0       1.0      0.0   
393  1.371370 -0.449535    0.0  1.0        0.0        0.0       1.0      0.0   
394 -0.047230 -0.242932    0.0  1.0        0.0        0.0       1.0      0.0   
395 -0.914152  0.437828    1.0  0.0        0.0        0.0       1.0      1.0   
396 -0.441286 -0.507796    0.0  1.0        0.0        1.0       0.0      0.0   
397  1.450181  0.782017    1.0  0.0        1.0        0.0       0.0      1.0   
398 -0.598908 -0.498385    0.0  1.0        0.0        0.0       1.0      0.0   
399  0.110392 -0.499132    0.0  1.0        0.0        1.0       0.0      0.0   
400  0.031581  2.317724    1.0  0.0        0.0        0.0       1.0      1.0   
401  0.662070 -0.261307    0.0  1.0        0.0        0.0       1.0      0.0   
402 -0.598908  0.427072    1.0  0.0        1.0        0.0       0.0      1.0   
403 -0.992964  0.206576    0.0  1.0        0.0        0.0       1.0      1.0   
404  1.056126 -0.140826    0.0  1.0        1.0        0.0       0.0      1.0   
405 -0.756530 -0.389257    0.0  1.0        1.0        0.0       0.0      0.0   
406 -0.520

In [80]:
log_reg.predict(df_test)
log_reg

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [123]:
Goal = pd.read_csv('./gender_submission.csv')

In [124]:
Real = Goal['Survived'].copy()
Real

0      0
1      1
2      0
3      0
4      1
5      0
6      1
7      0
8      1
9      0
10     0
11     0
12     1
13     0
14     1
15     1
16     0
17     0
18     1
19     1
20     0
21     0
22     1
23     0
24     1
25     0
26     1
27     0
28     0
29     0
      ..
388    0
389    0
390    0
391    1
392    0
393    0
394    0
395    1
396    0
397    1
398    0
399    0
400    1
401    0
402    1
403    0
404    0
405    0
406    0
407    0
408    1
409    1
410    1
411    1
412    1
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [97]:
log_reg.score(df_test,Real)

0.9138755980861244

In [82]:
Goal['log_reg'] = log_reg.predict(df_test)

In [122]:
Goal

PassengerId  Survived  for_reg
0            892         0        0
1            893         0        0
2            894         0        0
3            895         0        0
4            896         1        1
5            897         0        0
6            898         1        0
7            899         0        0
8            900         1        1
9            901         0        0
10           902         0        0
11           903         0        0
12           904         1        1
13           905         0        0
14           906         1        1
15           907         1        1
16           908         0        0
17           909         0        0
18           910         1        1
19           911         0        0
20           912         0        0
21           913         0        0
22           914         1        1
23           915         1        1
24           916         1        1
25           917         0        0
26           918         1        1
27           919         0        0
28           920         0        0
29           921         0        0
..           ...       ...      ...
388         1280         0        0
389         1281         0        0
390         1282         1        0
391         1283         1        1
392         1284         0        0
393         1285         0        0
394         1286         0        0
395         1287         1        1
396         1288         0        0
397         1289         1        1
398         1290         0        0
399         1291         0        0
400         1292         1        1
401         1293         0        0
402         1294         1        1
403         1295         1        0
404         1296         1        0
405         1297         0        0
406         1298         0        0
407         1299         0        0
408         1300         1        0
409         1301         1        1
410         1302         1        0
411         1303         1        1
412         1304         1        1
413         1305         0        0
414         1306         1        1
415         1307         0        0
416         1308         0        0
417         1309         0        0

[418 rows x 3 columns]

In [112]:
Goal['Survived'] = final_model.predict(df_test)

In [96]:
forest_reg.score(df_test,Real)

0.8660287081339713

In [113]:
Submission = Goal.drop('Survived',axis=1)
Submission.columns = ['PassengerId','Survived']

In [114]:
Submission.to_csv('./Submission_2.csv',index=False)

In [96]:
Submission.drop('index',axis=1)

KeyError: "['index'] not found in axis"

In [92]:
Submission.to_csv('./Submission.csv')

In [49]:
grid_search.best_estimator_.set_params

<bound method BaseEstimator.set_params of LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)>

In [98]:
df_2 = df.drop(['Embarked_Q','Pclass_2'],axis=1)
df_2.fillna(0,inplace=True)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\pandas\core\generic.py:3111: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [105]:
y = data['Survived'].copy()

In [112]:
log_reg.fit(df_2,y)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [113]:
log_reg.predict(df_2)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,

In [114]:
log_reg.score(df_2,y)

0.7901234567901234

In [115]:
y_test = Goal['Survived'].copy()

In [116]:
log_reg.score(df_test2,y_test)

0.9138755980861244

In [117]:
log_reg.predict(df_test2)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [119]:
from sklearn.tree import DecisionTreeClassifier
tree_cla = DecisionTreeClassifier()
tree_cla.fit(df_2,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [120]:
tree_cla.score(df_2,y)

0.9887766554433222

In [122]:
tree_cla.score(df_test2,y_test)

0.7751196172248804

In [69]:
final_model.fit(df_2,y)
final_model.score(df_2,y)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7957351290684624

In [68]:
final_model.score(X,y)
grid_search.best_estimator_.coef_

ValueError: X has 12 features per sample; expecting 10

In [70]:
final_model.score(df_test2,y_test)

NameError: name 'df_test2' is not defined

In [141]:
final_model.predict(df_test2)

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [147]:
Submit = test['PassengerId']
Submit['Survived'] = final_model.predict(df_test2)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [109]:
df_test.drop(['Embarked_Q','Pclass_2'],axis=1,inplace=True)

C:\Users\Seung kyu Hong\Anaconda3\lib\site-packages\pandas\core\generic.py:3111: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [156]:
final_model.predict(df_test)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [144]:
final_model.coef_

array([[-0.42188329,  0.02009303,  2.12082484, -0.41379659,  0.        ,
        -0.49033026,  0.92491768, -1.30357179, -0.04711094, -0.30693803]])

In [157]:
Submission['Survived'] = final_model.predict(df_test)
Submission.to_csv('./Submission_2.csv',index=False)

In [155]:
final_model.score(df_test,Real)

1.0